meta-data/scoreboard/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
</CustomObject>

meta-data/scoreboard/objects/Game__c.object
<CustomObject>
    <description>Custom Object for Individual Game Tracking</description>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quarter_1_Score_Team_1__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quarter 1 Score Team 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quarter_1_Score_Team_2__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quarter 1 Score Team 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quarter_2_Score_Team_1__c</fullName>
        <label>Quarter 2 Score Team 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quarter_2_Score_Team_2__c</fullName>
        <label>Quarter 2 Score Team 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quarter_3_Score_Team_1__c</fullName>
        <label>Quarter 3 Score Team 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quarter_3_Score_Team_2__c</fullName>
        <label>Quarter 3 Score Team 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quarter_4_Score_Team_1__c</fullName>
        <label>Quarter 4 Score Team 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quarter_4_Score_Team_2__c</fullName>
        <label>Quarter 4 Score Team 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sport__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sport</label>
        <referenceTo>Sport__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_1_Total_Score__c</fullName>
        <formula>Quarter_1_Score_Team_1__c +  Quarter_2_Score_Team_1__c +  Quarter_3_Score_Team_1__c +  Quarter_4_Score_Team_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Team 1 Total Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team 1</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_2_Total_Score__c</fullName>
        <formula>Quarter_1_Score_Team_2__c +  Quarter_2_Score_Team_2__c +  Quarter_3_Score_Team_2__c +  Quarter_4_Score_Team_2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Team 2 Total Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team 2</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Games (Team 2)</relationshipLabel>
        <relationshipName>Games1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Game</label>
    <nameField>
        <displayFormat>Game-{000000}</displayFormat>
        <label>Game Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

meta-data/scoreboard/objects/Highlight__c.object
<CustomObject>
    <fields>
        <fullName>Game__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>Highlights</relationshipLabel>
        <relationshipName>Highlights</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Highlight_Caption__c</fullName>
        <label>Highlight Caption</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Highlights</relationshipLabel>
        <relationshipName>Highlights</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Highlight</label>
    <nameField>
        <label>Highlights Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Highlights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

meta-data/scoreboard/objects/Sport__c.object
<CustomObject>
    <description>Category for Sports</description>
    <label>Sport</label>
    <nameField>
        <label>Sport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

meta-data/scoreboard/objects/Team__c.object
<CustomObject>
    <description>Custom Object to Track Teams</description>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

scoreboard-app/main/default/classes/PwaController.cls
@RestResource(UrlMapping='/v1/games/')
global with sharing class PwaController {


    public String body { get; set; }
    public String sessionId { get; set; }

    public class PwaDto {
        Contact contact { get; set; }
        Game__c[] games { get; set; }

    }

    global class PwaScoreDto {
        Id Id { get; set; }
        Integer Quarter_1_Score_Team_1 { get; set; }
        Integer Quarter_1_Score_Team_2 { get; set; }
        Integer Quarter_2_Score_Team_1 { get; set; }
        Integer Quarter_2_Score_Team_2 { get; set; }
        Integer Quarter_3_Score_Team_1 { get; set; }
        Integer Quarter_3_Score_Team_2 { get; set; }
        Integer Quarter_4_Score_Team_1 { get; set; }
        Integer Quarter_4_Score_Team_2 { get; set; }

        Game__c toGame() {
            return new Game__c(
                    Id = this.Id,
                    Quarter_1_Score_Team_1__c = this.Quarter_1_Score_Team_1,
                    Quarter_2_Score_Team_1__c = this.Quarter_2_Score_Team_1,
                    Quarter_3_Score_Team_1__c = this.Quarter_3_Score_Team_1,
                    Quarter_4_Score_Team_1__c = this.Quarter_4_Score_Team_1,
                    Quarter_1_Score_Team_2__c = this.Quarter_1_Score_Team_2,
                    Quarter_2_Score_Team_2__c = this.Quarter_2_Score_Team_2,
                    Quarter_3_Score_Team_2__c = this.Quarter_3_Score_Team_2,
                    Quarter_4_Score_Team_2__c = this.Quarter_4_Score_Team_2
            );
        }
    }

    public PwaController() {
        StaticResource pwaResource = [
                SELECT
                        Body
                FROM
                        StaticResource
                WHERE
                        Name = 'pwasw'
        ];

        System.debug(pwaResource);

        this.body = pwaResource.Body.toString();

        this.sessionId = UserInfo.getSessionId();

        System.debug('end constructor');

    }


    @RemoteAction
    public static PwaDto verifyEmail(String email) {

        PwaDto dto = new PwaDto();

        Contact contact = [
                SELECT
                        Id,
                        Name,
                        Email
                From
                        Contact
                WHERE
                        Email = :email

                LIMIT 1
        ];

        dto.contact = contact;

        Game__c[] games = [
                SELECT
                        Date__c,
                        Id,
                        Name,
                        OwnerId,
                        Quarter_1_Score_Team_1__c,
                        Quarter_1_Score_Team_2__c,
                        Quarter_2_Score_Team_1__c,
                        Quarter_2_Score_Team_2__c,
                        Quarter_3_Score_Team_1__c,
                        Quarter_3_Score_Team_2__c,
                        Quarter_4_Score_Team_1__c,
                        Quarter_4_Score_Team_2__c,
                        RecordTypeId,
                        Sport__c,
                        Sport__r.Name,
                        SystemModstamp,
                        Team_1__c,
                        Team_1__r.Name,
                        Team_1_Total_Score__c,
                        Team_2__c,
                        Team_2__r.Name,
                        Team_2_Total_Score__c, (
                        SELECT
                                Id,
                                Highlight_Caption__c,
                                Name,
                                Picture__c,
                                Team__r.Name,
                                Game__c
                        FROM
                                Highlights__r
                )

                FROM
                        Game__c

        ];

        dto.games = games;
        return dto;
    }

    @RemoteAction
    public static Game__c submitGame(PwaScoreDto score) {

        Game__c game = score.toGame();

        update game;

        return game;
    }

    @HttpGet global static String getGame() {
        return 'Test;';
    }

    @HttpPut
    global static Game__c[] putGame(String scoresString) {
        System.debug('START: putGame');
        System.debug(scoresString);

        PwaScoreDto[] scores = (PwaScoreDto[]) JSON.deserialize(scoresString, PwaScoreDto[].class);
        System.debug(scores);
        
        Game__c[] games = new List<Game__c>();

        for (PwaScoreDto score : scores) {
            games.add(PwaController.submitGame(score));

        }

        return games;
    }
}